//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBlogApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discussion()
        {
            this.DiscussionComments = new HashSet<DiscussionComment>();
            this.UserDiscussions = new HashSet<UserDiscussion>();
        }
    
        public int DiscussionID { get; set; }
        public string Title { get; set; }
        public string ContentText { get; set; }
        public string OwnerUsername { get; set; }
        public string OnwerProfileImage { get; set; }
        public bool Status { get; set; }
        public System.DateTime DatePosted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscussionComment> DiscussionComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDiscussion> UserDiscussions { get; set; }
    }
}
